framework:
    secret: '%env(APP_SECRET)%'
    router:
        utf8: true
    csrf_protection: true
    assets:
        enabled: true
    sessions:
        handler_id: null
    validation: { enabled: true }
    templating:
        engines: ['twig']
