security:
    enable_authenticator_manager: true

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    password_hashers:
        App\Entity\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: form_login # Définir "form_login" comme point d'entrée

            # Authentification avec formulaire
            form_login:
                login_path: app_login
                check_path: app_login

            # Authentification personnalisée (facultatif)
            custom_authenticator: App\Security\AppAuthentificatorAuthenticator

            logout:
                path: app_logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
